# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Rendezvous' do
	pod 'Parse'
	pod 'ALCameraViewController', '1.1.6'
end

